- name: remove /etc/tmux.conf
  become: true
  file:
    path: /etc/tmux.conf
    state: absent

- name: remove /usr/local/bin/tmux
  become: true
  file:
    path: /usr/local/bin/tmux
    state: absent

- name: remove /opt/tmux
  become: true
  file:
    path: /opt/tmux
    state: absent
