- name: create dir /opt/tmux
  become: true
  file:
    path: /opt/tmux
    state: directory

- name: download tmux.appimage
  become: true
  get_url:
    url: https://github.com/nelsonenzo/tmux-appimage/releases/download/3.5a/tmux.appimage
    dest: /opt/tmux
    mode: "0755"

- name: create link /usr/local/bin/tmux
  become: true
  file:
    src: /opt/tmux/tmux.appimage
    path: /usr/local/bin/tmux
    state: link

- name: copy tmux.conf to /etc/tmux.conf
  become: true
  copy:
    src: ../files/tmux.conf
    dest: /etc/tmux.conf
    mode: "0644"
