set -s focus-events on
set -sa terminal-features alacritty:RGB
set -sa terminal-features alacritty:hyperlinks

set -g history-limit 1000000
set -gw mode-keys vi
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 10
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -R 10
