set -sg escape-time 10
set -g default-terminal tmux-256color
set -ga terminal-features xterm-256color:RGB
set -ga terminal-features alacritty:RGB
set -g focus-events on
set -g allow-passthrough on
set -g history-limit 1000000
set -g mode-keys vi
