  - name: uninstall tmux config
    hosts: all
    become: true
    become_method: sudo
    tasks:
      - name: remove /etc/tmux.conf
        file:
            path: /etc/tmux.conf
            state: absent
