  - name: install tmux config
    hosts: all
    become: true
    become_method: sudo
    tasks:
      - name: copy tmux.conf to /etc/tmux.conf
        copy:
            src: ../files/tmux.conf
            dest: /etc/tmux.conf
            mode: '0644'
