  - name: install zellij
    hosts: all
    become: true
    become_method: sudo
    vars:
        download_uri: https://github.com/zellij-org/zellij/releases/download/v0.39.2/zellij-x86_64-unknown-linux-musl.tar.gz

    tasks:
      - name: remove /opt/zellij
        file:
            path: /opt/zellij
            state: absent

      - name: create dir /opt/zellij
        file:
            path: /opt/zellij
            state: directory

      - name: download and unarchive zellij
        unarchive:
            src: '{{ download_uri }}'
            remote_src: true
            dest: /opt/zellij

      - name: create link /usr/bin/zellij
        file:
            src: /opt/zellij/zellij
            path: /usr/bin/zellij
            state: link
            force: true

      - name: create link /usr/bin/tmux
        file:
            src: /opt/zellij/zellij
            path: /usr/bin/tmux
            state: link
            force: true
